export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    SIGNUP: '/registrarse',
    EMAIL_CONFIRMATION: '/confirmar-correo',
    VERIFY_EMAIL_PENDING: '/verificar-correo-pendiente',
    EMAIL_VERIFICATION: '/verificar-correo',
    PRIVACY_POLICY: '/aviso-de-privacidad',
    DASHBOARD: '/dashboard',
    VOUCHER_UPLOAD: '/subir-comprobante',
    VOUCHER_LIST: '/comprobantes',
    TRANSACTION_UPLOAD: '/transacciones',
    BANK_RECONCILIATION: '/conciliacion-bancaria',
    PAYMENT_MANAGEMENT: '/administracion-de-pagos',
    HISTORICAL_RECORDS_UPLOAD: '/carga-de-registros-historicos',
    USER_MANAGEMENT: '/administracion-de-usuarios',
    EXPENSE_REPORT: '/informe-de-gastos',
}